# Generated by Django 3.1.7 on 2022-01-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applink', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applink',
            name='name',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
    ]
